Release 3.17.0
GeotrekCE/Geotrek-rando-v3 pull request #1016
Opened 2024-01-10 10:15 UTC by dtrucs

2024-01-10 10:44 UTC, babastienne requested changes

2024-01-10 10:44 UTC, babastienne commented on docs/changelog.md
> +- Define customization for activity bar (#560)
```suggestion
- Define customization for activity bar (#560 and #568)
```

2024-01-11 10:49 UTC, babastienne approved these changes

2024-01-12 10:37 UTC, camillemonchicourt approved these changes

2024-01-12 10:39 UTC, dtrucs commented on docs/changelog.md
> +## 3.17.0 (2024-01-10)
```suggestion
## 3.17.0 (2024-01-12)
```

2024-01-12 10:40 UTC, merged