Rename attachments props to images props
GeotrekCE/Geotrek-rando-v3 pull request #1113
Opened 2024-04-18 13:35 UTC by dtrucs

Images and documents are provided by the API under an "attachments" key.

In GTR, only images are displayed, filtered by the key `type="image"`.
This key should be called "images", but it's actually "attachments". However, in a future development, "document" attachments will also be displayed, making the "attachments" key ambiguous.

To avoid this ambiguity, a renaming is necessary.

2024-04-18 13:45 UTC, camillemonchicourt approved these changes

2024-04-18 14:16 UTC, mabhub requested changes

2024-04-18 14:16 UTC, mabhub commented on frontend/src/components/ImageWithLegend/index.tsx
> +  const legend = [image?.legend, image?.author].filter(Boolean).join(' - ');
```suggestion
  const legend = [image.legend, image.author].filter(Boolean).join(' - ');
```

2024-04-18 14:16 UTC, mabhub commented on frontend/src/components/ImageWithLegend/index.tsx
> +        src={image?.url ? image.url : getGlobalConfig().fallbackImageUri}
```suggestion
        src={image.url || getGlobalConfig().fallbackImageUri}
```

```suggestion
        src={image.url || getGlobalConfig()?.fallbackImageUri}
```

2024-04-18 15:07 UTC, mabhub commented on frontend/src/components/pages/details/components/DetailsCard/DetailsCard.tsx
> +  images,
Maybe at app level, but not at the component level.
If `DetailsCard` is instanced without props, an exception will be thrown.

2024-04-18 15:28 UTC, dtrucs commented on frontend/src/components/pages/details/components/DetailsCard/DetailsCard.tsx
> +  images,
TypeScript won't let you do this! :sweat_smile:

2024-04-18 15:33 UTC, mabhub commented on frontend/src/components/pages/details/components/DetailsCard/DetailsCard.tsx
> +  images,
TypeScript is not present at runtime.  
Props may be conditionally provided based on data from external API.

2024-04-25 09:35 UTC, mabhub approved these changes

2024-04-25 16:00 UTC, merged