Publish docs on readthedocs
GeotrekCE/Geotrek-rando-v3 pull request #1254
Opened 2024-09-17 10:51 UTC by camillemonchicourt

2024-09-30 08:51 UTC, bruhnild commented
Changements visibles ici : https://geotrek-rando-v3.readthedocs.io/latest/

2024-09-30 09:11 UTC, camillemonchicourt commented on mkdocs.yml
> +copyright: Copyright &copy; 2024-<script>document.write(new Date().getFullYear())</script> <a href="https://makina-corpus.com/territoires">Makina Corpus Territoires</a>, Maintained by the <a href="ht
Selon moi on ne devrait pas mettre de copyright Makina Corpus.

2024-09-30 09:12 UTC, camillemonchicourt commented
OK pour moi (hormis le copyright), ça rend bien comme ça.

2024-09-30 09:15 UTC, bruhnild commented on mkdocs.yml
> +copyright: Copyright &copy; 2024-<script>document.write(new Date().getFullYear())</script> <a href="https://makina-corpus.com/territoires">Makina Corpus Territoires</a>, Maintained by the <a href="ht
Il y est sur la doc de GTA, j'ai repris le même principe  : https://geotrek.readthedocs.io/en/2.109.1/index.html

Mais ce n'est peut être pas pertinent. Que pourrait on mettre à la place ?

2024-09-30 09:23 UTC, camillemonchicourt commented on mkdocs.yml
> +copyright: Copyright &copy; 2024-<script>document.write(new Date().getFullYear())</script> <a href="https://makina-corpus.com/territoires">Makina Corpus Territoires</a>, Maintained by the <a href="ht
Pas de copyright selon moi.
Déjà car y en a pas selon moi, donc c'est faux.
Éventuellement la licence, les contributeurs, etc... 
Mais on a déjà ça par ailleurs dans le Github.

2024-09-30 09:49 UTC, camillemonchicourt commented
Par contre, j'avais identifié quelques soucis avec mkdocs.
Les code blocks ne peuvent pas être indenté comme mentionné ici :  https://www.mkdocs.org/user-guide/writing-your-docs/#fenced-code-blocks

Exemple ici de code bloc indenté : 
![image](https://github.com/user-attachments/assets/13c72f37-e746-4262-9098-7588d93032a4)

Non indenté est OK : 
![image](https://github.com/user-attachments/assets/7e53e0f1-2e6a-4bc9-a543-c21da79c5a7c)

La seule bonne solution pour cela semble être l'ajout de l'extension https://facelessuser.github.io/pymdown-extensions/extensions/superfences/, comme discuté ici : https://github.com/mkdocs/mkdocs/issues/282#issuecomment-393717991

-------------------------------------------------------

Et les notes, warning and co qui ne sont pas interprétés : 
![image](https://github.com/user-attachments/assets/56da8782-dd8a-4e2d-8cc5-159e9a82ba9c)
Alors que c'est le cas sur Github : 
![image](https://github.com/user-attachments/assets/bc24507a-23c9-4483-a8c5-e3ca569e1ec5)

Je ne les ai peut-être pas renseignés comme il faut. Je creuse un peu ça.

----------------------------

Après si `mkdocs` c'est pas idéal, j'ai pas de préférence d'outil.
Mais l'important est que ça soit simple à mettre en place, déployer et maintenir (installer le moins d'outils et d'extensions) pour que ça soit stable dans le temps, simple de contribuer (markdown idéal), et le plus homogène possible entre Geotrek-admin et Geotrek-rando en terme de présentation et d'affichage.

2024-09-30 12:55 UTC, bruhnild commented
J'ai réindenté les bouts de code et l'affichage est beaucoup mieux.

![image](https://github.com/user-attachments/assets/ed836e35-a896-4f95-87b8-646ad31fafdc)

2024-10-02 09:41 UTC, bruhnild commented
Nouveau thème Material for mkdocs ==> https://geotrek-rando-v3.readthedocs.io/latest/

2024-10-08 08:15 UTC, babastienne commented
Quelques sujets / questions : 

- Je trouve très bizarre d'un point de vue cohérence qu'il y ai tout en anglais SAUF la page "présentation générale" qui est en français. Pour moi soit on fait une doc complète en anglais soit on traduit tout en français et on laisse aux utilisateurs la possibilité de choisir une langue dans l'interface. C'est déjà un problème qu'on a sur Geotrek-Admin et ca serait chouette de ne pas le reproduire, autant le corriger maintenant sachant qu'il n'y a qu'une seule page à traduire en anglais. 
- A minima si on garde cette page telle quelle il faudra alors dans tous les liens qui pointent vers cette page mentionner à côté que c'est en français car sinon ce n'est vraiment pas clair d'un point de vue navigation où on passe sans avertissement d'une langue à une autre.
- Est-ce qu'on est obligés de mettre partout geotrek-rando **V3**. Y a-t-il encore besoin de distinguer les versions sachant que la v2 n'est plus maintenue et archivée ?
- Avant de merger : la PR a-t-elle été rebased sur la dernière release pour vérifier qu'on a bien toutes les dernières modifications de doc réalisées dans les dernières PR mergée ?

2024-10-08 08:58 UTC, camillemonchicourt commented
- Pour la partie PRESENTATION, en effet, c'est un peu bizarre. Mais en fait celle-ci était clairement destinée aux utilisateurs de la communauté, et non pas aux techniciens, raison pour laquelle je l'ai faite en français car sinon elle aurait perdu un peu sa cible. En fait c'est comme dans la doc de Geotrek-admin où le manuel utilisateur est en français, tandis que tout le reste de la doc est en anglais (car destiné à un public qui est plus familier avec cette langue). N'ayant pas le temps de faire les 2 langues pour tout et de les maintenir/mettre à jour, pour moi le compromis est acceptable. Je ne pense pas qu'on sera en capacité de gérer et mettre à jour toute la doc en 2 langues. En attendant doc utilisateur en FR et doc technique en EN est un compromis acceptable pour moi.
- OK pour moi de parler désormais de Geotrek-rando sans préciser V3

2024-10-11 11:51 UTC, bruhnild commented
J'ai retiré les mentions Rando V3 et précisé `(french)` lorsqu'une page fait référence à la page de présentation rédigée en français (https://geotrek-rando-v3.readthedocs.io/latest/presentation-fr/). 

J'ai voulu mettre en place un mécanisme de changement de langue (anglais/français) mais :
1) Est ce pertinent dans la mesure où il n'existe actuellement qu'un seule page en français dans la documentation ? Il est toujours possible de traduire l'ensemble des pages dans les deux langues mais comme dit Camille, je ne pense pas qu'on aura la capacité de maintenir ce fonctionnement sur la durée.
2) Semble techniquement plus compliqué que prévu (voir https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/)

2024-10-11 14:04 UTC, babastienne commented
@bruhnild pour moi pas besoin d'activer deux langues pour le moment. Si tu mentionné quand on mettais le lien que la page était français c'est suffisant. 

Merci pour la mise à jour de la doc. :pray: 

Je n'ai pas vérifié (pas assez de réseau pour charger la page de diff), mais il faut aussi en profiter pour mettre à jour le readme du projet et indiquer la lien vers la nouvelle doc.

Pour le reste c'est ok pour moi, on peut merger.

_______

Rien à voir, mais est-ce qu'on ne profiterai pas de cette "nouvelle" doc pour en faire la com' auprès de la communauté ? Un mail sur la mailing liste en mode "Heyyy, pour info voici la nouvelle doc GTR3 : <lien>. N'hésitez pas à aller la voir et à nous remonter sur ce ticket (insérer lien vers un ticket) si vous trouvez certaines choses manquantes ou peu claires, nous avons besoin de vos retours pour l’améliorer". Idem si vous avez des idées et souhaits de nouvelles fonctionnalités ou si vous identifiez des choses qui vous paraissent manquantes" ? Je me dis que ça pourrait être l'occasion d'obtenir des retours de la communauté car peut-être certaines personnes n'osent pas ou n'y pensent pas le reste du temps ?

2024-10-11 14:10 UTC, babastienne commented
@dtrucs peux-tu regarder le diff et voir si ça te semble ok de ton côté les modifs avant de merger ?

2024-10-11 14:25 UTC, bruhnild commented
Readme mis à jour.

2024-10-11 17:06 UTC, dtrucs commented
@bruhnild
1/ pourquoi avoir déplacé énormément de fichier dans un dossier `/fr/` ?
2/ rajouter une custo dans `/customization/`, je suis ok mais ça ne serait pas mieux de mettre quelque chose qui ressemble à geotrek plutôt que copier celle du département du 62? Je pense qu'il ne faudrait pas mettre de scriptsHeader (ou autre chose que des scripts analytics)

2024-10-11 17:06 UTC, dtrucs commented on mkdocs/requirements.txt
> +requests~=2.26
@submarcos could you review parts related to python stuff?

2024-10-14 08:26 UTC, camillemonchicourt commented
> @bruhnild 1/ pourquoi avoir déplacé énormément de fichier dans un dossier `/fr/` ? 2/ rajouter une custo dans `/customization/`, je suis ok mais ça ne serait pas mieux de mettre quelque chose qui ressemble à geotrek plutôt que copier celle du département du 62? Je pense qu'il ne faudrait pas mettre de scriptsHeader (ou autre chose que des scripts analytics)

- Oui là y a eu un soucis il me semble. Je pense pas que l'intégration de la custo d'un département soit volontaire.
- Et je ne comprends pas non plus tout le contenu duplique dans /fr/. A supprimer il me semble, on ne prévoit pas de maintenir une doc en EN et en FR. Seulement en EN pour tout le volet technique, et en FR pour la présentation générale.

2024-10-14 16:41 UTC, bruhnild commented
Effectivement, il y a eu un commit malheureux qui a embarqué des fichiers indésirables. Le dossier `/fr` a été supprimé ainsi que les fichiers de customization qui n'avaient rien à y faire. 
Le reste semble ok, ne manque plus que la review sur le fichier `requirements.txt`

2024-10-14 16:42 UTC, dtrucs commented
J'ai supprimé le dossier `/fr/` et la custo indésirable

2024-10-17 15:03 UTC, camillemonchicourt commented on docs/development/contributing.md
> +## Contributing to the Geotrek Rando product
```suggestion
## Contributing to Geotrek-rando source code
```

2024-10-17 15:04 UTC, camillemonchicourt commented on docs/development/contributing.md
> +- Make a fork of the projet and then install it following the [installation](./installation.md) guide.
```suggestion

- Make a fork of the projet and then install it following the [installation](./installation.md) guide.
```

2024-10-28 08:59 UTC, camillemonchicourt commented
Le fichier README.md sera aussi celui affiché sur la page d'accueil quand on arrive sur le Github : https://github.com/GeotrekCE/Geotrek-rando-v3
Et selon moi, en l'état il ne colle pas avec cet usage : https://github.com/GeotrekCE/Geotrek-rando-v3/blob/add-readthedocs/README.md

On ne devrait pas inclure ce README dans la documentation, et faire en sorte qu'il contienne le minimum nécessaire quand on arrive sur le Github du projet (image et texte de présentation de base, lien vers la doc...).

2024-10-31 10:17 UTC, bruhnild commented
- [Readme](https://github.com/GeotrekCE/Geotrek-rando-v3/blob/add-readthedocs/README.md) mis à jour avec de nouvelles sections (features, license, contribution, contributors, etc.)
- index.md (page d'accueil de la [doc](https://geotrek-rando-v3.readthedocs.io/latest/)) simplifié

2024-10-31 11:08 UTC, babastienne reviewed
Très chouette cette nouvelle page de readme.

Maintenant j'ai envie de faire la même chose sur GTA :laughing:

2024-10-31 11:08 UTC, babastienne commented on README.md
> +</p>
```suggestion
<p align="center">
<a href="https://geotrek-rando-v3.readthedocs.io/" rel="nofollow"><img alt="Documentation" src="https://img.shields.io/badge/Read%20the%20Docs-8CA1AF?logo=readthedocs&logoColor=fff" style="max-width:100%;"></a>
<a href="https://gtr3demo.ecrins-parcnational.fr/" rel="nofollow"><img alt="Démo gtr3 écrins" src="https://img.shields.io/badge/Demo-PN Ecrins-orange.svg" style="max-width:100%;"></a>
<a href="https://gtr3demo.ecrins-parcnational.fr/" rel="nofollow"><img alt="Démo gtr3 geotrek.fr" src="https://img.shields.io/badge/Demo-Geotrek.svg" style="max-width:100%;"></a>
<a href="https://matrix.to/#/%23geotrek:matrix.org" rel="nofollow"><img alt="Chat matrix" src="https://img.shields.io/badge/Matrix-000?logo=matrix&logoColor=fff" style="max-width:100%;"></a>
<a href="https://groups.google.com/g/geotrek-fr" rel="nofollow"><img alt="Google group" src="https://img.shields.io/badge/Google-group-red.svg" style="max-width:100%;"></a>
</p>

<p align="center">
<a href="https://github.com/GeotrekCE/Geotrek-rando-v3/releases/latest" rel="nofollow"><img alt="Release" src="https://img.shields.io/github/release/GeotrekCE/Geotrek-rando-v3.svg" style="max-width:100%;"></a>
<a href="https://github.com/GeotrekCE/Geotrek-rando-v3/actions/workflows/e2e.yml" rel="nofollow"><img alt="Status Test E2E" src="https://github.com/geotrekce/Geotrek-rando-v3/actions/workflows/e2e.yml/badge.svg" style="max-width:100%;"></a>
<a href="https://github.com/GeotrekCE/Geotrek-rando-v3/actions/workflows/e2e.yml" rel="nofollow"><img alt="Status Test E2E" src="https://github.com/geotrekce/Geotrek-rando-v3/actions/workflows/action-intall-and-test.yml/badge.svg" style="max-width:100%;"></a>
<a href="https://github.com/GeotrekCE/Geotrek-rando-v3/actions/workflows/e2e.yml" rel="nofollow"><img alt="Status Test E2E" src="https://github.com/geotrekce/Geotrek-rando-v3/actions/workflows/release.yml/badge.svg" style="max-width:100%;"></a>
</p>
```

2024-10-31 11:08 UTC, babastienne commented on README.md
> +2. Launch the app at [localhost:3000](http://localhost:3000)
Enelver cette section car redondant avec la section "Develeper documentation" ? Ou à minima la mettre à un niveau de titre inférieure car liée à la documentation de développement.

2024-10-31 11:26 UTC, bruhnild commented on README.md
> +2. Launch the app at [localhost:3000](http://localhost:3000)
Ok, c'est redondant en effet, je retire cette section.

2024-10-31 11:27 UTC, camillemonchicourt commented on README.md
> +Demo available at [https://gtr3demo.ecrins-parcnational.fr](https://gtr3demo.ecrins-parcnational.fr).
On pourrait aussi mettre directement 2 ou 3 exemples de vrais portails pour montrer des vrais usages, moins basiques, non ?
Mettre les liens des admins, etc... pourquoi pas, mais faut pas que ça devienne un peu complexe de s'y retrouver dans trop de liens et d'infos. Pas d'avis tranché donc.

2024-10-31 13:24 UTC, bruhnild commented on README.md
> +Demo available at [https://gtr3demo.ecrins-parcnational.fr](https://gtr3demo.ecrins-parcnational.fr).
J'ai créé une section "Examples of Geotrek-rando portals" avec 4 randos + un montage d'images pour illustrer.

2024-10-31 13:25 UTC, bruhnild commented on README.md
> +Demo available at [https://gtr3demo.ecrins-parcnational.fr](https://gtr3demo.ecrins-parcnational.fr).
pour les liens de l'admin je n'ai rien fait pour l'instant, pas trop d'idée sur la façon de les présenter dans le readme.

2024-10-31 13:36 UTC, dtrucs requested changes

2024-10-31 13:36 UTC, dtrucs commented on README.md
> +You can find two demonstration website at the following addresses :
```suggestion
You can find two demonstration websites at the following links:
```

2024-10-31 13:36 UTC, dtrucs commented on README.md
> +<a href="https://gtr3demo.ecrins-parcnational.fr/" rel="nofollow"><img alt="Démo gtr3 geotrek.fr" src="https://img.shields.io/badge/Demo-Geotrek.svg" style="max-width:100%;"></a>
```suggestion
<a href="https://gtr3demo.ecrins-parcnational.fr/" rel="nofollow"><img alt="Geotrek Rando demo by Ecrins National Park" src="https://img.shields.io/badge/Demo-PN Ecrins-orange.svg" style="max-width:100%;"></a>
<a href="https://demo-rando.geotrek.fr/" rel="nofollow"><img alt="Geotrek Rando demo" src="https://img.shields.io/badge/Demo-Geotrek.svg" style="max-width:100%;"></a>
```

2024-11-04 10:26 UTC, dtrucs approved these changes

2024-11-12 12:55 UTC, babastienne commented
@dtrucs go pour merger cette PR ?

2024-11-12 16:26 UTC, merged