Define go back button on details pages
GeotrekCE/Geotrek-rando-v3 pull request #1303
Opened 2024-11-14 09:03 UTC by dtrucs

ref https://github.com/GeotrekCE/Geotrek-rando-v3/issues/1282

2024-11-14 11:17 UTC, babastienne requested changes
Can you add some information in the documentation to explain how to hide the button ? You did it in the dedicated issue but imo it should also be documented in the official documentation.

2024-11-19 10:08 UTC, dtrucs commented
@babastienne 
> Can you add some information in the documentation to explain how to hide the button ? You did it in the dedicated issue but imo it should also be documented in the official documentation.

The documentation already talks about style overrides (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization/customization-themestyles.md#css): 
> In addition, some classes prefixed with `custo-*` are gradually being added to facilitate style overrides for components.

I'm not sure it's relevant to document how to display or not **this** element with CSS in the App. In that case, where's the limit? Because everything could be hidden...

2024-11-19 10:28 UTC, camillemonchicourt commented
> @babastienne
> 
> > Can you add some information in the documentation to explain how to hide the button ? You did it in the dedicated issue but imo it should also be documented in the official documentation.
> 
> The documentation already talks about style overrides (https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/docs/customization/customization-themestyles.md#css):
> 
> > In addition, some classes prefixed with `custo-*` are gradually being added to facilitate style overrides for components.
> 
> I'm not sure it's relevant to document how to display or not **this** element with CSS in the App. In that case, where's the limit? Because everything could be hidden...

Yes, I agree with that. I would not add it in the global customization, but good to have it in the dedicated issue as actually.

2024-11-19 12:54 UTC, babastienne approved these changes

2024-11-19 13:03 UTC, merged