Fix/ssr-navigator
GeotrekCE/Geotrek-rando-v3 pull request #674
Opened 2022-06-02 12:24 UTC by JordaneNS

## Détails de la PR :
Lors du pull de la branche develop, 2 bugs sont apparus : 

- une erreur "navigator is not defined" apparaissait lors du premier rendu d'une page. Pour éviter cette erreur j'ai ajouté dans les affichages conditionnels `typeof navigator !== "undefined"`
- une erreur de SSR est apparue sur la page de la randonnée (id: 501). L'erreur nous dit qu'il est impossible de serializer une valeur qui est undefined. Et effectivement sur cette rando il apparaît que le signage["703"].imageUrl renvoyé par l'api est undefined : 
![image](https://user-images.githubusercontent.com/99249234/171627567-450a34a8-5f01-4f53-b0fb-cabe55f115b3.png)

L'erreur n'est pas présente sur la démo mais je pense qu'il est quand même important de la régler.
Pour se faire, je suis passée par la méthode `SanitizeState `déjà utilisée sur la page search.tsx afin d'éviter l'erreur de serialization.

## Screenshots
- Erreur du navigator 
![image](https://user-images.githubusercontent.com/99249234/171627183-a999ca1d-331b-4483-8244-610dcd4106ce.png)

- Erreur SSR trek/[detailsId]
![image](https://user-images.githubusercontent.com/99249234/171627359-5685b334-b760-439a-9ba5-c76b97d3c79d.png)

2022-06-02 13:34 UTC, dtrucs commented
Hello,
Bien vu pour l'erreur SSR de `signage`! 👍 
Cela dit tu n'aurai pas dû t'embêter avec ça et ouvrir un ticket. En ayant implémenté cette partie, donc ce bug, j'aurai pris la responsabilité du fix.

Je pense que ton fix est peut-être un peu overkill, et ça contourne le prefetching de `React-query`.

Remplacer cette ligne 
https://github.com/GeotrekCE/Geotrek-rando-v3/blob/main/frontend/src/modules/signage/adapter.ts#L9
par
`imageUrl: rawSignage.attachments?.find(({ type }) => type === 'image')?.thumbnail ?? null,`
(+ répercuter la modification sur le typage `s/undefined/null`) pour cette prop devrait faire le taf.

Je propose de retirer ton commit et tu me dis si tu (ou je) fais le fix ci-dessus.

Pour le reste de la PR, parfait 👍

2022-06-03 08:09 UTC, JordaneNS commented
Hello @dtrucs ! 
Merci pour ton retour !
Je me suis occupée du fix : j'ai bien pris en compte les modifications et les erreurs sur le typage :)

2022-06-03 08:26 UTC, dtrucs requested changes

2022-06-03 08:26 UTC, dtrucs commented on frontend/src/modules/signage/interface.ts
> +  imageUrl: string | undefined | null;
idem

2022-06-14 07:27 UTC, JordaneNS commented
@dtrucs ok it's done

2022-06-14 07:29 UTC, dtrucs approved these changes

2022-06-14 07:50 UTC, merged