Features/add sensitive areas to outdoors
GeotrekCE/Geotrek-rando-v3 pull request #683
Opened 2022-06-03 10:10 UTC by JordaneNS

## Détails de la PR

- ajout des zones sensibles sur les parcours outdoor

## Screenshots

![image](https://user-images.githubusercontent.com/99249234/171834830-18c341ca-ef19-4e51-ac9d-25ffa7b26565.png)

2022-06-09 09:10 UTC, dtrucs requested changes

2022-06-09 09:10 UTC, dtrucs commented on frontend/src/modules/sensitiveArea/api.ts
> +      ? { ...query, period: 'ignore', near_outdoorcourse: id }
Maybe you can DRY this code
```js
const typeKey = type.startsWith('outdoor') ? `near_${type.toLowerCase()}` : 'trek';
const params = { ...query, period: 'ignore', [typeKey]: id }
```

2022-06-10 07:28 UTC, JordaneNS commented on frontend/src/modules/sensitiveArea/api.ts
> +      ? { ...query, period: 'ignore', near_outdoorcourse: id }
Ok done ;)

2022-06-10 08:41 UTC, dtrucs approved these changes

2022-06-10 09:04 UTC, merged